print('new line from vs code 1')
print('new line from github 1')
print ('new line from vs code new branch')
print ('new line from vs code main branch')
print ('new line from github main branch')
print(5+8)
print(9+98)
print(9)
